app = "justsploit-api"
primary_region = "sin"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8000"
  ENVIRONMENT = "production"

[deploy]
  release_command = "python -c 'import app.models; from app.db.session import engine; from app.models.base import Base; Base.metadata.create_all(bind=engine)'"

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services.tcp_checks]]
  grace_period = "1s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"