services:
  - type: web
    name: justsploit-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: justsploit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CELERY_BROKER_URL
        value: memory://
      - key: CELERY_RESULT_BACKEND
        value: memory://
      - key: ENVIRONMENT
        value: production

databases:
  - name: justsploit-db
    databaseName: justsploit
    user: justsploit